#ifndef _LIBRADAUTH_DICT_H
#define _LIBRADAUTH_DICT_H
static char *dictionary_rfc2865 =
	"# -*- text -*-\n"
	"#\n"
	"#	Attributes and values defined in RFC 2865.\n"
	"#	http://www.ietf.org/rfc/rfc2865.txt\n"
	"#\n"
	"#	$Id$\n"
	"#\n"
	"ATTRIBUTE	User-Name				1	string\n"
	"ATTRIBUTE	User-Password				2	string\n"
	"ATTRIBUTE	CHAP-Password				3	octets\n"
	"ATTRIBUTE	NAS-IP-Address				4	ipaddr\n"
	"ATTRIBUTE	NAS-Port				5	integer\n"
	"ATTRIBUTE	Service-Type				6	integer\n"
	"ATTRIBUTE	Framed-Protocol				7	integer\n"
	"ATTRIBUTE	Framed-IP-Address			8	ipaddr\n"
	"ATTRIBUTE	Framed-IP-Netmask			9	ipaddr\n"
	"ATTRIBUTE	Framed-Routing				10	integer\n"
	"ATTRIBUTE	Filter-Id				11	string\n"
	"ATTRIBUTE	Framed-MTU				12	integer\n"
	"ATTRIBUTE	Framed-Compression			13	integer\n"
	"ATTRIBUTE	Login-IP-Host				14	ipaddr\n"
	"ATTRIBUTE	Login-Service				15	integer\n"
	"ATTRIBUTE	Login-TCP-Port				16	integer\n"
	"# Attribute 17 is undefined\n"
	"ATTRIBUTE	Reply-Message				18	string\n"
	"ATTRIBUTE	Callback-Number				19	string\n"
	"ATTRIBUTE	Callback-Id				20	string\n"
	"# Attribute 21 is undefined\n"
	"ATTRIBUTE	Framed-Route				22	string\n"
	"ATTRIBUTE	Framed-IPX-Network			23	ipaddr\n"
	"ATTRIBUTE	State					24	octets\n"
	"ATTRIBUTE	Class					25	octets\n"
	"ATTRIBUTE	Vendor-Specific				26	octets\n"
	"ATTRIBUTE	Session-Timeout				27	integer\n"
	"ATTRIBUTE	Idle-Timeout				28	integer\n"
	"ATTRIBUTE	Termination-Action			29	integer\n"
	"ATTRIBUTE	Called-Station-Id			30	string\n"
	"ATTRIBUTE	Calling-Station-Id			31	string\n"
	"ATTRIBUTE	NAS-Identifier				32	string\n"
	"ATTRIBUTE	Proxy-State				33	octets\n"
	"ATTRIBUTE	Login-LAT-Service			34	string\n"
	"ATTRIBUTE	Login-LAT-Node				35	string\n"
	"ATTRIBUTE	Login-LAT-Group				36	octets\n"
	"ATTRIBUTE	Framed-AppleTalk-Link			37	integer\n"
	"ATTRIBUTE	Framed-AppleTalk-Network		38	integer\n"
	"ATTRIBUTE	Framed-AppleTalk-Zone			39	string\n"
	"\n"
	"ATTRIBUTE	CHAP-Challenge				60	octets\n"
	"ATTRIBUTE	NAS-Port-Type				61	integer\n"
	"ATTRIBUTE	Port-Limit				62	integer\n"
	"ATTRIBUTE	Login-LAT-Port				63	string\n"
	"\n"
	"#\n"
	"#	Integer Translations\n"
	"#\n"
	"\n"
	"#	Service types\n"
	"\n"
	"VALUE	Service-Type			Login-User		1\n"
	"VALUE	Service-Type			Framed-User		2\n"
	"VALUE	Service-Type			Callback-Login-User	3\n"
	"VALUE	Service-Type			Callback-Framed-User	4\n"
	"VALUE	Service-Type			Outbound-User		5\n"
	"VALUE	Service-Type			Administrative-User	6\n"
	"VALUE	Service-Type			NAS-Prompt-User		7\n"
	"VALUE	Service-Type			Authenticate-Only	8\n"
	"VALUE	Service-Type			Callback-NAS-Prompt	9\n"
	"VALUE	Service-Type			Call-Check		10\n"
	"VALUE	Service-Type			Callback-Administrative	11\n"
	"\n"
	"#	Framed Protocols\n"
	"\n"
	"VALUE	Framed-Protocol			PPP			1\n"
	"VALUE	Framed-Protocol			SLIP			2\n"
	"VALUE	Framed-Protocol			ARAP			3\n"
	"VALUE	Framed-Protocol			Gandalf-SLML		4\n"
	"VALUE	Framed-Protocol			Xylogics-IPX-SLIP	5\n"
	"VALUE	Framed-Protocol			X.75-Synchronous	6\n"
	"\n"
	"#	Framed Routing Values\n"
	"\n"
	"VALUE	Framed-Routing			None			0\n"
	"VALUE	Framed-Routing			Broadcast		1\n"
	"VALUE	Framed-Routing			Listen			2\n"
	"VALUE	Framed-Routing			Broadcast-Listen	3\n"
	"\n"
	"#	Framed Compression Types\n"
	"\n"
	"VALUE	Framed-Compression		None			0\n"
	"VALUE	Framed-Compression		Van-Jacobson-TCP-IP	1\n"
	"VALUE	Framed-Compression		IPX-Header-Compression	2\n"
	"VALUE	Framed-Compression		Stac-LZS		3\n"
	"\n"
	"#	Login Services\n"
	"\n"
	"VALUE	Login-Service			Telnet			0\n"
	"VALUE	Login-Service			Rlogin			1\n"
	"VALUE	Login-Service			TCP-Clear		2\n"
	"VALUE	Login-Service			PortMaster		3\n"
	"VALUE	Login-Service			LAT			4\n"
	"VALUE	Login-Service			X25-PAD			5\n"
	"VALUE	Login-Service			X25-T3POS		6\n"
	"VALUE	Login-Service			TCP-Clear-Quiet		8\n"
	"\n"
	"#	Login-TCP-Port		(see /etc/services for more examples)\n"
	"\n"
	"VALUE	Login-TCP-Port			Telnet			23\n"
	"VALUE	Login-TCP-Port			Rlogin			513\n"
	"VALUE	Login-TCP-Port			Rsh			514\n"
	"\n"
	"#	Termination Options\n"
	"\n"
	"VALUE	Termination-Action		Default			0\n"
	"VALUE	Termination-Action		RADIUS-Request		1\n"
	"\n"
	"#	NAS Port Types\n"
	"\n"
	"VALUE	NAS-Port-Type			Async			0\n"
	"VALUE	NAS-Port-Type			Sync			1\n"
	"VALUE	NAS-Port-Type			ISDN			2\n"
	"VALUE	NAS-Port-Type			ISDN-V120		3\n"
	"VALUE	NAS-Port-Type			ISDN-V110		4\n"
	"VALUE	NAS-Port-Type			Virtual			5\n"
	"VALUE	NAS-Port-Type			PIAFS			6\n"
	"VALUE	NAS-Port-Type			HDLC-Clear-Channel	7\n"
	"VALUE	NAS-Port-Type			X.25			8\n"
	"VALUE	NAS-Port-Type			X.75			9\n"
	"VALUE	NAS-Port-Type			G.3-Fax			10\n"
	"VALUE	NAS-Port-Type			SDSL			11\n"
	"VALUE	NAS-Port-Type			ADSL-CAP		12\n"
	"VALUE	NAS-Port-Type			ADSL-DMT		13\n"
	"VALUE	NAS-Port-Type			IDSL			14\n"
	"VALUE	NAS-Port-Type			Ethernet		15\n"
	"VALUE	NAS-Port-Type			xDSL			16\n"
	"VALUE	NAS-Port-Type			Cable			17\n"
	"VALUE	NAS-Port-Type			Wireless-Other		18\n"
	"VALUE	NAS-Port-Type			Wireless-802.11		19\n";

#endif
